[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["backend"]
known_third_party = ["fastapi", "sqlmodel", "pydantic"]
skip = [".gitignore", ".dockerignore", ".env", "env.local", ".venv", "venv", "node_modules"]